### ISSUE TITLE
[DQT] Rendering issue with HTML UI elements of certain instruments

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#5092] opened 2019-08-23 19:29 UTC
DQT - Rendering issue with HTML UI elements of certain instruments (see image of frontend DQT display issues for example)

Not IBIS-specific.

Many more UI elements have been incorporated into instruments recently to help patients/parents filling them out directly, so the issue is now really glaring for certain instruments as it's almost every field broken on the front end.

![Bug_HTML_rendering_code-frontend_2018-11-7](https://user-images.githubusercontent.com/54332302/63618736-cd45bf80-c5ba-11e9-91f1-9ec0e97f7de4.JPG)

https://redmine.cbrain.mcgill.ca/issues/15607

**Comment by ridz1208** [comment] 2019-08-23 19:44
My guess is that this is caused by your instrument fields containing HTML which is not recommended.

removing HTML and rerunning the data dictionary builder should fix the issue

**Comment by johnsaigle** [comment] 2019-11-27 17:23
Closing because this is a "won't fix" issue. Instead, this should be documented as not being supported/recommended. I've opened a ticket for this.

**Closed by johnsaigle** 2019-11-27 17:23 UTC
