### ISSUE TITLE
[instrument_manager] Error got during uploading instrument.

### ISSUE THREAD

**Issue by racostas** [aces/Loris#8756] opened 2023-06-08 16:03 UTC
**Describe the bug**
When uplaoding and instrument throw the instrument_manager and error is got. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. MainMenu->Admin->Instrument Manager (having the permission `instrument_manager_write` granted)
2. Try to upload and instrument (ample .linst instrument file` test_all_fields.linst` in `test/instruments` suggested in the Test Plan)
3. See error
![image](https://github.com/aces/Loris/assets/37309344/6ff6e5af-acd8-4d4d-8aca-0f0f094a6b9f)

**What did you expect to happen?**
The file to be properly uploaded.

**Browser Environment (please complete the following information):**
- MsWindows
- Chrome Version 114.0.5735.110 (Official Build) (64-bit)

**Server Environment (if known):**
- Loris 25 candidate release.

**Comment by driusan** [comment] 2023-06-08 19:22
@zaliqarosli Since this was on copn-stg and it might be backend/configuration related I'm assigning it to you.

**Comment by driusan** [comment] 2023-10-17 18:11
This was caused by a misconfiguration as per comment on #8786

**Closed by driusan** 2023-10-17 18:11 UTC
Labels: Bug, 25.0.0 - Bugs
