### ISSUE TITLE
[imaging_uploader] Fields in upload form should be enabled when selecting 'no' for phantom scan

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#5520] opened 2019-11-04 19:17 UTC
When selecting `no` in the `Phantom Scan` field, other fields should be enabled. This is currently not the case.

![image](https://user-images.githubusercontent.com/34260251/68150385-a20e1380-ff0d-11e9-85d2-b496fc398f25.png)

**Comment by jesscall** [comment] 2019-11-04 19:20
I noticed however that when you attach a scan to be uploaded, it automatically fills out the candidate info + visit label based on the name of the file attached. The fields still remain disabled however. 

Is this the intended behaviour? 
@cmadjar @nicolasbrossard 

![image](https://user-images.githubusercontent.com/34260251/68150700-48f2af80-ff0e-11e9-9cd2-85faebe7f145.png)

**Comment by nicolasbrossard** [comment] 2019-11-04 20:09
I am using an older version of the uploader and you definitely have to fill these fields for candidate scans. I am afraid I can't tell if this has changed and what you are seeing is the new intended behaviour...

**Comment by cmadjar** [comment] 2019-11-05 18:45
@jesscall @nicolasbrossard This is the intended behaviour now. The fields get automatically populated based on the filename.

See https://github.com/aces/Loris/issues/2909

Closing this issue since this is the intended behaviour.

**Closed by cmadjar** 2019-11-05 18:45 UTC
Labels: 22.0.0 TESTING, Bug, UI

**Comment by driusan** [comment] 2019-11-05 18:47
Does the test plan need to be updated?

**Comment by cmadjar** [comment] 2019-11-05 19:56
No, it was already updated :)
