### ISSUE TITLE
[survey_accounts] All surveys give Error 500 when trying to complete survey

### ISSUE THREAD

**Issue by SantiagoTG** [aces/Loris#8021] opened 2022-02-25 17:07 UTC
**Describe the bug**
Error 500 is given when clicking 'Save and Continue' on first page of any of the surveys, regardless of status, candidate, visit or entry to the fields.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to the survey accounts module
2. Search for a given survey
3. Click on URL to access survey (error is also present if accessing survey via emailed link)
4. Fill out fields on first page
5. Click the 'Save and Continue' button

**What did you expect to happen?**
You should progress to next page of survey.

**Browser Environment (please complete the following information):**
- Chrome

**Additional context**
Related to: https://github.com/aces/Loris/issues/8020

**Comment by CamilleBeau** [comment] 2022-03-01 20:07
This appears to be because LorisFormDictionaryImpl is passing a null value as lorisinstance to NDB_BVL_Instrument::factory. I'm not clear on where lorisinstance is meant to be set for LorisFormDictionaryImpl, @ridz1208 @driusan do you have insight on this?

**Comment by driusan** [comment] 2022-03-07 21:08
All NDB_Page types (including instruments) should have a `$this->loris` property that I think should be able to be used

**Comment by CamilleBeau** [comment] 2022-03-08 12:20
> All NDB_Page types (including instruments) should have a `$this->loris` property that I think should be able to be used

@driusan NDB_BVL_Instrument gets its `$this->loris` instance after instantiation right? From the error below it looks like the problem is that LorisFormDictionaryImpl has a null loris instance, and is passing that null value as a LorisInstance to NDB_BVL_Instrument::factory when instantiating the instrument.

`[Tue Mar 08 07:16:33.620355 2022] [php7:error] [pid 23539] [client 192.168.122.1:45774] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to NDB_BVL_Instrument::factory() must be an instance of LORIS\\LorisInstance, null given, called in /var/www/ccna/php/libraries/LorisFormDictionaryImpl.class.inc on line 159 and defined in /var/www/ccna/project/libraries/NDB_BVL_Instrument.class.inc:223\nStack trace:\n#0 /var/www/ccna/php/libraries/LorisFormDictionaryImpl.class.inc(159): NDB_BVL_Instrument::factory(NULL, 'CTU_Baseline_Mi...')\n#1 /var/www/ccna/project/libraries/NDB_BVL_Instrument.class.inc(1542): NDB_BVL_Instrument_CTU_Surveys->getDataDictionary()\n#2 /var/www/ccna/project/libraries/NDB_BVL_Instrument.class.inc(2386): NDB_BVL_Instrument->getFieldValue('Date_taken')\n#3 /var/www/ccna/project/libraries/NDB_BVL_Instrument.class.inc(669): NDB_BVL_Instrument->getCandidateAge('2021-01-01')\n#4 /var/www/ccna/project/libraries/NDB_BVL_Instrument.class.inc(795): NDB_BVL_Instrument->_saveCandidateAge(Array)\n#5 /var/www/ccna/php/libraries/LorisForm.class.inc(1453): NDB_BVL_Instrument->_saveValues(Array)\n#6 /var/www/ccna/pr in /var/www/ccna/project/libraries/NDB_BVL_Instrument.class.inc on line 223, referer: https://ccna-dev.loris.ca/survey.php?key=f6cd6f4445d6032a
`

**Comment by driusan** [comment] 2022-03-15 14:02
fixed by above PR

**Closed by driusan** 2022-03-15 14:02 UTC
Labels: Bug, Critical to release, 24.0.0-bugs
