### ISSUE TITLE
[document_repository] Delete File permission access to module

### ISSUE THREAD

**Issue by pierre-p-s** [aces/Loris#6578] opened 2020-05-22 02:11 UTC
The delete File permission does not let the user view the module as it is explained in the test plan.

Update test plan or update the permission for access to the module.

**Comment by johnsaigle** [comment] 2020-05-25 15:20
Duplicate of #6373. 

Agreed that we should either fix this or update the test plan.

**Comment by ridz1208** [comment] 2020-05-27 15:01
closed for duplication

**Closed by ridz1208** 2020-05-27 15:01 UTC
Labels: 23.0.0-testing, Bug
