### ISSUE TITLE
[Issue Tracker] filter issue

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6141] opened 2020-03-09 15:30 UTC
**Describe the bug**
issue_tracker#Active Issues

will show issues with status "New" and at the same time filter will be changed to "Closed", the issue is not "closed" in fact.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to 'issue tracker'
2. Click on 'new issue'
3. click the "Active Issues" tab, you will see that the filter status changes to "Closed", the same as "Closed Issues" tab, which is not correct.

**What did you expect to happen?**
If not "closed", then either shows that status, or nothing in the filter instead of the "Closed", which will be the same filter as "Closed" tab

**Browser Environment (please complete the following information):**
- Browser: firefox
- Version: v23

Possibly the same issue exists on the other versions, I did not check.

**Comment by lingma** [comment] 2020-03-09 15:31
Possibly the same issue exists on other versions, I did not check.

**Comment by christinerogers** [comment] 2020-05-11 13:21
@driusan @ridz1208 Any reason this shouldn't be assigned to someone for the 23 release?

**Comment by christinerogers** [comment] 2020-05-11 16:59
@spell00 Can you reproduce this on your sandbox? 
If so, try a PR for this to the 23 branch.

**Comment by spell00** [comment] 2020-05-11 18:26
I was not able to reproduce this issue in my sandbox

**Comment by christinerogers** [comment] 2020-05-11 18:30
closing this.  Neither I nor Simon @spell00 can reproduce on Chrome or Firefox on test-loris-dev

**Closed by christinerogers** 2020-05-11 18:30 UTC
Labels: 23.0.0-testing, Bug

**Comment by lingma** [comment] 2020-05-11 19:04
I can reproduce this:

![image](https://user-images.githubusercontent.com/5295785/81601331-b2a9b580-9398-11ea-8dec-405c27df4e15.png)
