### ISSUE TITLE
[Data Release] Can't remove permissions under Manage Permissions

### ISSUE THREAD

**Issue by Jkat** [aces/Loris#5708] opened 2019-11-20 20:09 UTC
Unchecking permissions and saving doesn't do anything

**Comment by ridz1208** [comment] 2019-11-22 19:40
@Jkat could you give steps to reproduce ?
i just tried it out and it seems to be working

**Comment by Jkat** [comment] 2019-11-22 20:13
I uncheck one of the checked boxes under Manage Permissions for a user and it doesn't seem to save this change. Looks like unchecking both(/all) boxes works...

**Comment by ridz1208** [comment] 2019-11-25 16:47
@Jkat nice catch !! 

it was a edge case when the version file is 0

**Comment by driusan** [comment] 2019-11-26 18:19
PR merged

**Closed by driusan** 2019-11-26 18:19 UTC
Labels: 22.0.0 TESTING, Bug, Critical to release, PR sent
