### ISSUE TITLE
[dataquery] Manage Saved Queries tab not working

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#5501] opened 2019-11-01 22:01 UTC
Clicking on the Manage Saved Queries tab does not do anything...

**Comment by johnsaigle** [comment] 2019-11-11 16:19
I'm not able to reproduce this on `aces/22.0-release` or on the test VM. I'm going to close this but if I'm wrong please feel to re-open and let me know what I've missed.

**Closed by johnsaigle** 2019-11-11 16:19 UTC
Labels: 22.0.0 TESTING, Bug, Critical to release
