### ISSUE TITLE
User password modification problem

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6086] opened 2020-02-20 15:26 UTC
**Describe the bug**
On V21.05, if a user is expired, the system will ask to change password. I have tried no less than 10 times, no matter what kind of strong password you entered, the system will say that the password is not strong enough or the password does not match. This kind of user experience is quite crazy at least for me. This behavior has impact to the existing users of v21, which will be confused on what happened.

Loris V22 is correct, the expiration date will be pushed.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
Find a expired user, then login, the system will ask you to change it on v21.

**What did you expect to happen?**
A clear information on what it is, if not able to modify, then tell me.

**Browser Environment (please complete the following information):**
- Version: 21.05

**Server Environment (if known):**
- LORIS Version: [e.g. 21.0.0] 21.0.5

**Comment by johnsaigle** [comment] 2020-02-24 16:02
Possible duplicate of #4208 

Do you know what the cause of the issue is? Is it the password expiry, password complexity, or passwords not matching?

**Comment by lingma** [comment] 2020-02-24 16:05
I will check if necessary. I feel that this is not password complexity or not matching, not urgent, since only 21 has this problem, I tested, 22 is fine

**Comment by johnsaigle** [comment] 2020-02-24 16:13
Since this isn't an issue on 21 I think we'll likely close this issue as "won't fix" since we don't tend to support old versions of LORIS.

@driusan @ridz1208 Let me know if this should be closed.

**Comment by lingma** [comment] 2020-02-24 16:16
Right, v22 is correct. This is not a password complexity issue, because my password is complicate enough to pass v22. The same or even more complicate won't work on v21. I did not further check because I was busy with other issues

**Comment by johnsaigle** [comment] 2020-02-24 16:18
> my password is complicate enough to pass v22. The same or even more complicate won't work on v21.

Version 22 isn't exactly "more complicated" than version 21. They have different rule sets. It's possible that a valid password in 22 would be invalid in 21 since 21 requires special characters.

**Comment by lingma** [comment] 2020-02-24 16:19
Well, of course I should have provided special characters as the rules asked.

**Comment by johnsaigle** [comment] 2020-02-24 16:21
OK, just double checking.

**Comment by lingma** [comment] 2020-02-24 16:21
Let me check if I can find something in 21, if not, I will just give up.

**Comment by lingma** [comment] 2020-02-24 16:58
I am sorry for having mixed up, in fact the reason is that `?` is not recognized as a special character, which I happened to have used. Effectively, V22 doesn't check in this way, so the password modification could go ahead.

**Closed** 2020-02-24 16:59 UTC
Labels: Bug

**Comment by lingma** [comment] 2020-02-24 17:06
I saw that the code supports \ and & but those won't show up as the allowed characters.
