### ISSUE TITLE
[new_profile] Gives an error that the 'Date of Birth' is invalid when 'DOB format' is set to 'YM'

### ISSUE THREAD

**Issue by shonibare** [aces/Loris#8567] opened 2023-04-05 16:31 UTC
**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to the 'Configuration' module and set the 'DOB format' to 'YM'
2. Then go to the 'New profile' module, enter information for the new candidate
3. Click submit

**What did you expect to happen?**
- It should allow the information to be saved

**Browser Environment (please complete the following information):**
- OS: [e.g. Plan9, HURD, Oberon, etc]
- Browser [e.g. chrome, firefox] (note that only these two browsers are supported)

**Server Environment (if known):**
_Note: We only support the most recent release of LORIS._
- LORIS Version: [e.g. 22.0.0]
- Linux distribution and Version: [e.g. Ubuntu 16.04, CentOS 7]
- MySQL/MariaDB Version: [e.g. MySQL 5.7, MariaDB 10.3]

**Additional context**
related to #8516

**Comment by xlecours** [comment] 2023-04-12 18:16
@CamilleBeau can you tell if this is a duplicate of https://github.com/aces/Loris/issues/8586 ?

**Comment by xlecours** [comment] 2023-04-12 18:17
It is

**Closed by xlecours** 2023-04-12 18:17 UTC
Labels: Bug, 25.0.0 - Bugs
