### ISSUE TITLE
[User account] Add/Edit user form - Required fields

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#6556] opened 2020-05-20 17:32 UTC
In User account > New User, required fields are not indicated in the form with (*).
The form asks for many pieces of information, such visual help can efficiently improve UX.

**Comment by johnsaigle** [comment] 2020-05-20 20:56
Duplicate of #5218.

That said I definitely agree that this would be a great improvement. User Accounts is not dynamic/does not use ReactJS right now and so it doesn't benefit from the UX advantages that other parts of LORIS have right now.

**Closed** 2020-05-20 21:01 UTC
Labels: Proposal

**Comment by christinerogers** [comment] 2020-05-21 19:18
I'm pretty sure this used to be a feature and may have been removed at some point, because we wanted all fields filled out as much as possible (institution, address, etc). 
I'd start by checking release 16/17 to see if it was removed before or after then.

**Comment by laemtl** [comment] 2020-05-22 21:29
@christinerogers I checked the history of the [template file](https://github.com/aces/Loris/blob/23.0-release/modules/user_accounts/templates/form_edit_user.tpl) and didn't find any trace of previous required annotations.
