### ISSUE TITLE
[MRI Violations] Missing help text for sub-pages

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#6575] opened 2020-05-21 21:27 UTC
**Describe the bug**
On the testing VM, I did not see any help for the `Resolved Violations`, `MRI Protocol Check Violations` and `MRI Protocol Violations` pages. The main page had some (little...) help text though.

**To Reproduce**
Access the pages mentioned above in the MRI violations module and check the help text.

**Comment by johnsaigle** [comment] 2020-06-08 20:12
This is still missing in the latest round of testing.

**Comment by christinerogers** [comment] 2020-06-08 22:26
@nicolasbrossard @johnsaigle This issue is a duplicate of #5714

It was previously reported for the 22 release. 
@ridz1208 let's just close it for the 23release and resolve #5714 instead. (For 23 or master, up to you, i don't think it's urgent now.)
5714 can also be updated with a note about the Resolved violations page missing text.

**Comment by christinerogers** [comment] 2020-06-09 15:36
closing this and putting @nicolasbrossard (who volunteered) on #5714

**Closed by christinerogers** 2020-06-09 15:36 UTC
Labels: 23.0.0-testing, Documentation
