### ISSUE TITLE
[Imaging Browser] project filter ComboBox shows all projects (including the ones the user doesn't have permissions to see)

### ISSUE THREAD

**Issue by racostas** [aces/Loris#6691] opened 2020-06-09 00:27 UTC
**Describe the bug**
This seems to be a minor issue.

The `Project filter ComboBox` shows all projects (including the ones the user doesn't have permissions to see). In the other hand the results for querying projects where the user doesn't have permissions are not been shown in the result table which is a good thing. 

**To Reproduce**
1. Go to Imaging -> Imaging Browser
2. Click on the `Project ComboBox`
3. The user is able to see and choose projects it doesn't have permission to access.

**What did you expect to happen?**
In step number 3 the user should be able to see and choose only from the project it have access.

**Comment by driusan** [comment] 2023-11-21 15:11
Duplicate of #6829 (which is more thorough)

**Closed by driusan** 2023-11-21 15:11 UTC
Labels: Bug
