### ISSUE TITLE
[23.0][DICOM archive] Patient name should not be shown in result table

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7208] opened 2020-12-15 15:47 UTC
Issue originally reported by @nicolasbrossard on CCNA Repo during candidate release testing of LORIS 23.0.2
aces/CCNA#4289
___
As user testadmin, I accessed the Configuration module and set both the patient ID and patient name regex to `JGH0174`. This should basically hide the patient ID and patient name for every candidate except this guy. I accessed the DICOM archive module and observed this in the result table:

- the patient ID and patient name column of the result table were visible for `JGH0174` 
- for all other candidates , the patient ID was set to `INVALID - HIDDEN` but the patient name was still visible (it should also have been set to `INVALID - HIDDEN`).

When accessing the details of a specific archive, the patient ID and patient name were correctly displayed or hidden so the bug seems to occur only in the result table.

**Comment by cmadjar** [comment] 2020-12-15 20:57
@jesscall @nicolasbrossard I was not able to reproduce the bug so I decided to test on the ccna-dev.loris.ca and noticed the following configurations:

- Patient ID regex => `JGH0174`
- Patient name regex => `JGH0174`
- Lego phantom regex => `.`
- Living phantom regex => `.`

Because the Living and Lego phantom regex for the patient name was set to `.`, the Patient Name was being displayed regardless of the Patient name regex config.

I restricted the regex for phantoms in the config to `phantom` and now, the Patient Name are indeed hidden for all subjects but `JGH0174`. :-)

@jesscall @nicolasbrossard if you confirm, could you close the issue as this is not a bug? Thanks!

**Comment by nicolasbrossard** [comment] 2020-12-16 14:03
@cmadjar I checked and when both the lego and living phantom regex are set to `.`, the patient name is visible in the result table **but** hidden in the DICOM archive detail page (when you click in the Metadata column). It's a bug IMHO, but my original description of it is wrong.  ;)

**Comment by cmadjar** [comment] 2020-12-16 14:26
aaaaaaaah, yep. Looks like a bug in the metadata page ;). Thank you for the detailed explanation. Sorry I missed that...

**Comment by driusan** [comment] 2020-12-18 13:50
Was fixed by #7231, not sure why it wasn't autoclosed.

**Closed by driusan** 2020-12-18 13:50 UTC
Labels: 23.0.0-testing, Bug
