### ISSUE TITLE
[document_repository] No e-mail notifications

### ISSUE THREAD

**Issue by CamilleBeau** [aces/Loris#6688] opened 2020-06-08 20:03 UTC
**Describe the bug**
No e-mail notifications are sent when a different user makes changes on `document_repository` after having the notifications enables in `My Preferences`. 

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to `My Preferences`
2. Enable all of the notifications relevant to document repository (make sure to save)
3. Make another user with a different email and edit document repository from that user by:
- Uploading new file
- Deleting file
- Editing file
- making a new category
4. Monitor whether you get email notifications for this. 

**What did you expect to happen?**
I expected to receive an e-mail for the changes made by the new user.

**Comment by johnsaigle** [comment] 2020-06-08 20:31
Is this a duplicate of #6580?

**Comment by CamilleBeau** [comment] 2020-06-08 21:57
@johnsaigle Yes, sorry about that! I can close it?

**Comment by johnsaigle** [comment] 2020-06-09 14:19
No problem! Yes I think that would be a good idea. Your description is much more detailed though so I think the best move would be to paste what you've written here into a comment on that issue.

**Closed** 2020-06-09 14:24 UTC
Labels: 23.0.0-testing, Bug
