### ISSUE TITLE
Block navigation away from page if forms modified and not saved

### ISSUE THREAD

**Issue by gdevenyi** [aces/Loris#5867] opened 2019-12-17 17:25 UTC
Right now, its possible to go through the entire QC page and set things and then navigate away from the page before saving. Javascript should be added to prevent this for any pages with more the NNN (to be determined) fields to prevent input data loss.

**Comment by johnsaigle** [comment] 2019-12-17 18:20
Duplicate of #5100

**Closed** 2019-12-17 19:16 UTC
Labels: Proposal
