### ISSUE TITLE
[survey_accounts] Can't return to first page of Medical History survey 

### ISSUE THREAD

**Issue by suzanne-lee** [aces/Loris#7673] opened 2021-10-04 13:45 UTC
**Describe the bug**
After completing the first page of Medical History, if you try to go back to it, you get a 500 error. This issue is specific to returning to the first page; for example, if you try to go from page 3 to page 2, it works. 

**To Reproduce**
1. Go to the survey_accounts module and click a URL for a Medical History survey
2. Fill out the first page (Date of Admin & Examiner)
3. Go to the next page 
4. Fill out the second page and click "Save and Go Back" 

**Browser Environment**
- Chrome 93.0.4577.82
- Firefox 92.0.1

**Comment by cmadjar** [comment] 2023-01-10 15:21
@sruthymathew123 This might be fixed by https://github.com/aces/Loris/pull/7809, could you verify and if so close the issue? Thanks!

**Comment by sruthymathew123** [comment] 2023-01-26 15:13
I tested and couldn't recreate the issue. So I assume the issue is fixed.  So; closing the ticket.

**Closed by sruthymathew123** 2023-01-26 15:13 UTC
Labels: Bug, 24.0.0-bugs
