### ISSUE TITLE
Examiner Module 24.0 does not work when you click on an examiner from the table

### ISSUE THREAD

**Issue by LeighMac** [aces/Loris#7721] opened 2021-10-18 12:06 UTC
**Describe the bug**
A clear and concise description of what the bug is

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Go to '.EXAMINER MODULE
2. Click on 'ANY USER IN THE TABLE'
3.WHEN YOU CLICK ON ANY USER YOU ARE BROUGHT TO A PAGE: '.Go to main page or report an issue. If you have any questions, please contact your project administrator.

**Comment by ridz1208** [comment] 2021-11-16 11:56
@LeighMac I could not reproduce the error from either admin or regular user. Which user did you log in as ?

![image](https://user-images.githubusercontent.com/15268287/141981030-0ab4df9e-0700-4af3-912d-014e78bd1be3.png)

![image](https://user-images.githubusercontent.com/15268287/141981112-6eb4e529-5022-4fd9-8b8f-187707245eb2.png)

**Comment by jesscall** [comment] 2021-12-07 16:24
I could not reproduce the error either. 
Closing this.

**Closed by jesscall** 2021-12-07 16:24 UTC
Labels: Bug, 24.0.0-bugs
