### ISSUE TITLE
Candidate_list & instrument_list project filter problem

### ISSUE THREAD

**Issue by lingma** [aces/Loris#6928] opened 2020-08-20 23:27 UTC
**Describe the bug**
candidate_list `Project` filter option is useless since the candidate_list is filtered by project, the option is redundant.
instrument_list is not filtered by project, I don't know whether this is on purpose or not

**What did you expect to happen?**
As the above description

**Server Environment (if known):**
- LORIS Version: main

**Additional context**
originally reported by @nicolasbrossard in PR #6423 review

**Comment by christinerogers** [comment] 2020-08-26 17:06
this bug is a duplicate of #6829. 

There is a pr already in progress on this : https://github.com/aces/Loris/pull/6836 
it's been awaiting feedback for a few weeks now --

**Comment by christinerogers** [comment] 2020-08-26 17:12
this bug is a duplicate of #6829 -- closing this issue. 

There is a PR already in progress on this : https://github.com/aces/Loris/pull/6836 
it's been awaiting feedback for a few weeks now -- 
@lingma @nicolasbrossard if you have time to pull / comment / review that PR, please feel free.

**Closed by christinerogers** 2020-08-26 17:12 UTC
Labels: Bug

**Comment by lingma** [comment] 2020-08-26 21:25
I believe @6829 is not the same as this one, this one talks about the duplication and the instrument_list not filtered by project.

**Comment by driusan** [comment] 2020-09-01 13:56
The `candidate_list` being filtered by project doesn't mean the filter shouldn't be there since there can be more than 1 project for a user, but what project are you saying `instrument_list` should be filtered by?

**Comment by lingma** [comment] 2020-09-01 14:55
By user's associated projects
