### ISSUE TITLE
[RB] Assign multiple scans to some session 

### ISSUE THREAD

**Issue by laemtl** [aces/Loris#8558] opened 2023-04-05 15:49 UTC
In order to fully test the Brainbrowser, we need a session with multiple scans/volumes. Can we reassign some of the scans to sessions such that this is testable for future releases?

**Comment by cmadjar** [comment] 2023-04-11 14:53
Looks like an imaging browser issue as it only displays one image per session since only one of the scans is showed for each session. Check out latest 25.0 code and latest RB data and check if that is  reproducible.

**Comment by cmadjar** [comment] 2023-04-11 19:04
once latest code for 25 has been pulled on test 25, there will be multiple scans viewable per session in the imaging browser, allowing for BB testing. Should we close this @laemtl?

**Comment by cmadjar** [comment] 2023-04-11 19:05
@kongtiaowang any chance you could pull the latest 25.0-release code on testing?

**Comment by xlecours** [comment] 2023-04-12 17:22
N/A

**Closed by xlecours** 2023-04-12 17:22 UTC
Labels: Critical to release, RaisinBread, Proposal, 25.0.0 - Bugs
