### ISSUE TITLE
[next_stage] 404 error 

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#7032] opened 2020-09-14 18:55 UTC
Point 6 of the test plan for next_stage: 
Click the submit button when registering the stage - gives a 404 Not found  (no other error message) 
occurred on this candidate: 
Tried and reproduced on test-loris-dev.ca for: 
* https://test-loris-dev.loris.ca/next_stage/?candID=269819&sessionID=2162&identifier=2162
* https://test-loris-dev.loris.ca/next_stage/?candID=300147&sessionID=2163&identifier=2163

**To Reproduce**
Add a candidate and then a timepoint and then start next stage. Enter legit values

**Comment by driusan** [comment] 2020-09-22 20:42
This seems to be a duplicate of #7015. If I'm mistaken please reopen

**Closed by driusan** 2020-09-22 20:42 UTC
Labels: Bug

**Comment by christinerogers** [comment] 2020-09-22 20:46
seems to be the same.  maybe worth checking the same testing point is covered in both test plans. that's really the only point of the next_stage module

**Comment by christinerogers** [comment] 2020-12-15 20:05
update from CCNA testing: this error did not occur on ccna-dev
