### ISSUE TITLE
[instrument_list] Cannot select BVL QC Type or BVL QC Status

### ISSUE THREAD

**Issue by leighevans** [aces/Loris#4584] opened 2019-05-14 19:45 UTC
Instrument data entry and DDE is complete with no conflicts and Send to DCC is not available (even with Send to DCC permission and visit set to Pass), and clicking on any box for BVL QC (e.g. Visual, Hardcopy) does not register nor does clicking Complete for BVL QC Status as a result. 

![Screen Shot 2019-05-14 at 3 40 26 PM](https://user-images.githubusercontent.com/32552953/57727195-d5f33500-765e-11e9-9b6a-58407eaa39ba.png)

**Comment by zaliqarosli** [comment] 2019-05-16 19:44
@ridz1208 i can't reproduce this bug because all the instruments (except bmi) break so we can't bring the timepoint to the approval stage

**Comment by zaliqarosli** [comment] 2019-05-16 19:54
https://github.com/aces/Loris/issues/4641

**Comment by zaliqarosli** [comment] 2019-05-22 21:54
i fixed the BVLQCType issue (you can now click on it and it submits) @leighevans if you would like to test https://github.com/aces/Loris/pull/4683

**Comment by zaliqarosli** [comment] 2019-06-03 18:05
PR for BVLQCType issue merged. PR for Send to DCC issue still needs to be made by @kchatpar

**Comment by ridz1208** [comment] 2019-06-04 19:55
I guess its 50% done, repoened.

@kchatpar please issue PR

**Comment by sruthymathew123** [comment] 2019-06-07 16:15
@zaliqa I am trying to catch up the things to work on this issue. But, I cannot reproduce the issue (Send to DCC) on my VM or on test.loris.ca anymore. Is that fixed already?
![send_to_DCC](https://user-images.githubusercontent.com/23702452/59118273-b7125680-891d-11e9-8755-faf796fa8be9.png)

**Comment by zaliqarosli** [comment] 2019-06-07 19:02
@sruthymathew123 i don't think it was fixed yet. @kchatpar can you verify? if 'Send to DCC' is available and working for you, i'm happy to close this issue. let me know!

**Comment by sruthymathew123** [comment] 2019-06-10 19:27
@kchatpar Can you verify if this issue(Send to DCC not available) is still existing?

**Comment by sruthymathew123** [comment] 2019-06-11 16:31
@driusan @kchatpar @zaliqarosli  I don't know for some reason 'Send to DCC' is not clickable on **test.loris.ca** even if instrument data entry and DDE is complete with no conflicts and visit set to Pass.

But on my VM with IBIS data;  I couldn't recreate this issue. So I doubt it might be a RB data issue or test VM specific issue.  If anyone can test this on their own VM, that will help to move forward with this issue.

**Comment by cmadjar** [comment] 2019-06-11 17:11
@driusan @kchatpar @zaliqarosli I just tested this on my sandbox which has the latest RB dataset. I could click on the 'Send to DCC' after making sure all instruments were entered and no conflicts were present in the conflict resolver between the initial entry and DDE. I was also able to do it on testing which was just updated on the latest code. 

My guess is that the issue was fixed but the code not yet pulled on testing when you tried @sruthymathew123. Maybe try again now and close the issue if you can click on "Send to DCC"?

**Comment by sruthymathew123** [comment] 2019-06-11 17:56
Finally all confusions are cleared. Thanks @cmadjar for helping me to sort out this,
On test VM some visits don't have a clickable 'send to DCC' (even if all conditions satisfied) because that visits somehow got empty 'Registered By' (user who started the visit is empty)
Ex: https://test.loris.ca/instrument_list/?candID=300135&sessionID=2084
https://test.loris.ca/300135 (All the time points of this candidate have empty 'Registered By')

But all other valid time points are showing  clickable 'send to DCC' when the conditions are satisfied.
Ex: https://test.loris.ca/instrument_list/?candID=947103&sessionID=2159
https://test.loris.ca/947103 (This candidate have got valid timepoints with 'Registered By')

So I think we can close this issue.

**Comment by driusan** [comment] 2019-06-11 17:57
I think we should fix the data in raisinbread before closing the issue, so it doesn't get "detected" again in the future

**Comment by zaliqarosli** [comment] 2019-06-11 18:29
@sruthymathew123 nice! thanks for figuring this out! @kchatpar are you still okay to go ahead with fixing the issue?

**Comment by kchatpar** [comment] 2019-06-11 18:37
Thanks, @sruthymathew123 and @cmadjar! Yes, I will go ahead and make the fix I'll ping you if I get stuck @zaliqarosli

**Comment by zaliqarosli** [comment] 2019-06-11 18:38
@kchatpar start with `/raisinbread/README.md`. i think you will find it helpful!

**Comment by sruthymathew123** [comment] 2019-06-11 18:53
@kchatpar If you are going ahead to fix RB data; look into `/raisinbread/RB_files/RB_session.sql`. Replace all the `NULL` values added for 'Registered By` column as `admin`. Hope this helps!

**Comment by driusan** [comment] 2019-06-18 20:24
fixed by above

**Closed by driusan** 2019-06-18 20:24 UTC
Labels: 21.0.0 Testing, Critical to release, PR sent, RaisinBread, UI
