### ISSUE TITLE
[Statistics : Bvl ] Users can access other sites' instrument data without permission

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#2772] opened 2017-04-26 22:23 UTC
Reported by @um4r12  via loris-dev listserv : 

In the statistics module, from the Behavioural Statistics tab, and under "Per Instrument Stats" for any site, users can view incomplete forms from other sites (although they cannot edit them), even though they do not have the 'access_all_profiles' permission. So if an instrument hasn't been flagged as 'Complete', but data has been entered, users from other sites are able to access that information through the Statistics module.

**Comment by johnsaigle** [comment] 2018-10-17 21:32
@christinerogers I wasn't able to reproduce this. Here is what happened:
1. Create a new user: every permission but the "across all sites" ones, active in Ottawa and also an examiner in Ottawa
2. Go to Statistics
3. Go to Behavioural Statistics
4. Click on Per Instrument Stats for Montreal
5. Got an access denied message
6. Click on Per Instrument Stats for Rome
7. Access denied message
8. Click on Per Instrument Stats for Ottawa
9. Incomplete Candidate info appears, but only for Ottawa candidates.

This was done on a fresh `aces/major` with the Raisinbread dataset.

Could you check if this is still as issue? It's possible my dataset doesn't have the right information to allow me to reproduce this. 

If it's no longer an issue, would you mind closing this ticket?

**Comment by johnsaigle** [comment] 2018-10-18 15:40
@um4r12 Maybe you can weigh in here also?

**Comment by ridz1208** [comment] 2019-07-11 02:46
I will assume this is stale since it did not show up in the 21 testing

**Closed by ridz1208** 2019-07-11 02:46 UTC
Labels: Discussion Required
