### ISSUE TITLE
score_instruments.php is causing double escaping on each run

### ISSUE THREAD

**Issue by ejoh1101** [aces/Loris#7140] opened 2020-11-23 23:07 UTC
Running score_instruments.php is causing double escaping on each run

To Reproduce - 
Run `php tools/data_integrity/score_instruments.php all inprogress`. 

I specifically was running "all inprogress" but I imagine this happens for all scoring updates with this script. I verified this script was causing the issue by running the instrument_double_escape_fix.php script from @ridz1208 to remove all instances of double escaping and then running the score_instruments script. 

LORIS v23.0.2
php 7.3.11

**Comment by ridz1208** [comment] 2020-11-24 13:34
Hi @ejoh1101,

Which version of LORIS is this happening on ?

**Comment by ejoh1101** [comment] 2020-11-24 16:38
@ridz1208 I'm running LORIS version 23.0.2

**Comment by ridz1208** [comment] 2020-11-27 21:46
@jesscall is this still happening for you guys as well ?

**Comment by ridz1208** [comment] 2020-11-27 21:53
@ejoh1101 I know that the database class escapes HTML characters when inserting and updating. I suspect that the score_instrument.php script is fetching the data without ever decoding it and then resubmitting it. My only confusion is the following: this script only calls the `score()` function of the instrument it's scoring and that should only be calling save on the specific score fields and not resaving every value in the instrument...

so where are you seeing double escaping? do your score field contain special characters ? or is the score function resaving the entire instrument data ?

**Comment by jesscall** [comment] 2020-12-01 18:31
No, we don't have the double escape issue on CCNA anymore.

I believe the issue is with `_nullScores()` from `NDB_BVL_Instrument.class.inc`. 
Here's an override we have on CCNA so that only the score fields are submitted:

```
   function _nullScores(array $scoreCols): void
    {
        /******************* CCNA OVERRIDE START ******************/
        $record = $this->loadInstanceData($this);
        $scoreCols = array_combine($scoreCols, $scoreCols);
        // order is important here because it keeps values of first array
        // unsetting all columns which are not scores
        $data = array_intersect_key($record, $scoreCols);
        /******************* CCNA OVERRIDE END ******************/

	// set the scoring cols to NULL
        foreach ($scoreCols as $key => $val) {
            // Some Instruments use an associative array for
            // $scoreCols of the form column => description, others
            // use a non-associative array. So if the key is numeric,
            // and we need to make sure we use the column name
            if (is_numeric($key)) {
                $data[$val] = null; //null array
            } else {
                $data[$key] = null;
            }

        }

        $this->_save($data);
        return;
    }
```

@ejoh1101 Let me know if this resolves your issue, and I can submit this as a bugfix to LORIS

**Comment by ridz1208** [comment] 2020-12-02 15:42
@jesscall I just confirmed this issue still exists in 23 and main. please submit your bugfix to LORIS ASAP

**Comment by driusan** [comment] 2020-12-22 21:28
PR merged

**Closed by driusan** 2020-12-22 21:28 UTC
Labels: Bug, Critical to release
