### ISSUE TITLE
[mri_violations] Scrolling

### ISSUE THREAD

**Issue by jesscall** [aces/Loris#7203] opened 2020-12-14 21:49 UTC
Issue originally reported by @pierre-p-s on CCNA Repo during candidate release testing of `LORIS 23.0.2`
aces/CCNA#4280
____
When using a filter, you cannot scroll through the table data (scroll to the right to see problem or resolution status). Same thing when using the arrow

**Comment by zaliqarosli** [comment] 2020-12-17 21:22
@pierre-p-s im not able to recreate this issue. were you not able to scroll down or scross?

**Comment by jesscall** [comment] 2020-12-17 21:23
across but only when there is something in the filter

**Comment by driusan** [comment] 2020-12-18 14:28
What browser? Any plugins installed?

**Comment by pierre-p-s** [comment] 2020-12-18 16:00
I wasnt able to scroll across after searching with the filters. The table was buggy and brought me back to the begining of the table. I was using chrome. The table worked fine without the filters

**Comment by zaliqarosli** [comment] 2020-12-18 16:47
I tried scrolling across both with and without filters and i got no issues besides the general bugginess of it. the table is suuper buggy though and i tried to find the fix for this before (on statistics module) to no avail. im not able now to find any issues with the scrolling itself though, and don't think it has anything to do with the filtering

**Comment by pierre-p-s** [comment] 2020-12-18 17:25
I tried it on test-loris-dev.loris.ca and couldnt reproduce the error but if you go on ccna-dev.loris.ca you can reproduce the problem easily

**Comment by jesscall** [comment] 2020-12-18 17:28
@ridz1208 mentioned that this was an issue he's had in the past and that the carousel scrolling is known to be problematic. Can also be dependent on the size/resolution of screen and zoom.

**Comment by zaliqarosli** [comment] 2020-12-18 18:39
yeahh its something that i don't think I would be able to fix right now because I'm not sure what creates the problem. I just tried on ccna-dev.loris.ca and had no issues scrolling. i do believe that this happens for some users though. just don't know how to proceed

**Comment by SantiagoTG** [comment] 2021-10-04 22:20
This issue still occurs on test site (v24.0) when scrolling in the results table for specific search results and not others. For example, when searching for 'Visit label Visit1 does not exist in Visit_Windows' or 'CandID does not exist', the table jumps back to the left when scrolling right. This does not happen in other cases (eg. when searching for 'Protocol violations', table can be scrolled to the left).

Duplicate issue: https://github.com/aces/Loris/issues/5075

**Closed** 2021-11-11 21:04 UTC
Labels: Bug, 24.0.0-bugs
