### ISSUE TITLE
[install centOS] Visiting http://ip-address/installdb.php

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#5452] opened 2019-10-31 19:13 UTC
When visiting the installdb.php this output is thrown in loris-error.log:
`[Thu Oct 31 15:04:26.512944 2019] [php7:error] [pid 9728] [client ::1:45454] PHP Fatal error:  Uncaught Error: Class 'PDO' not found in /var/www/loris/php/installer/Installer.class.inc:143\nStack trace:\n#0 /var/www/loris/htdocs/installdb.php(71): LORIS\\Installer\\Installer->checkSystemDependenciesValid()\n#1 {main}\n  thrown in /var/www/loris/php/installer/Installer.class.inc on line 143`

**Comment by maltheism** [comment] 2019-10-31 19:55
Okay the error is solved with these packages:
```
sudo yum install php-pdo
sudo yum install php-pdo_mysql
```

**Comment by johnsaigle** [comment] 2019-11-04 17:05
Seems to be a duplicate of #5490

**Comment by driusan** [comment] 2019-11-20 19:56
Pr merged

**Closed by driusan** 2019-11-20 19:56 UTC
Labels: 22.0.0 TESTING, Bug, PR sent
