### ISSUE TITLE
Password rules are incorrect

### ISSUE THREAD

**Issue by thomasbeaudry** [aces/Loris#5962] opened 2020-01-27 19:35 UTC
On the Edit User's page, the password rules are outlined as:

    The password must be at least 8 characters long.
    The password cannot be your username or email address.

This is not in fact true, since the password that you choose has to also contain a special character or else you get the error message:   The password is not complex enough.  For example,  If you try the password:  **iamsosmrt**   you will see that it isn't accepted, but **iamsosmrt!**  is.

**Comment by thomasbeaudry** [comment] 2020-01-27 21:19
oops sorry @cmadjar, i didn't realize i was on LORIS-MRI repo

**Comment by gdevenyi** [comment] 2020-01-28 01:33
I reported issues with the password rules here:
https://github.com/aces/Loris/issues/3314

Which resulted in a PR here:
https://github.com/aces/Loris/pull/3962

Eventually changes were merged:
https://github.com/aces/Loris/pull/4411

But this issue indicates the password rules do not yet follow NIST standards?

**Comment by gdevenyi** [comment] 2020-01-28 01:33
Possibly waiting on this https://github.com/aces/Loris/issues/5761

**Comment by johnsaigle** [comment] 2020-01-28 18:00
The password rules aren't incorrect. The error message generated for that input is `The password is not complex enough.`, which is true. We use [Zxcvbn](https://github.com/dropbox/zxcvbn) to evaluate password strength according to NIST standards (see [this post](https://github.com/aces/Loris/issues/3314#issuecomment-534233065)). 

A special character isn't required; a sufficiently complex password is. The password `sufficientlengthandcomplexity` is a valid password in LORIS because its length alone gives it sufficient entropy so that it cannot be easily cracked by bruteforce password cracking software.

We have unit tests for passwords to confirm that weak passwords are rejected and that strong passwords are acceptable.

If you want to evaluate the strength of a given password I invite you to check out the tool https://lowe.github.io/tryzxcvbn/ which is an interactive demo of the library we use to evaluate password strength.

Also, there's a final line of text under the Password Rules you've quoted: 

> We suggest using a password manager to generate one for you.

**Closed by johnsaigle** 2020-01-28 18:00 UTC

**Comment by thomasbeaudry** [comment] 2020-01-29 17:34
I still think the rules could be written clearer.  For instance   iamsosmrt1  is rejected, but iamsosmrt!  passes the test (which is why i assumed it needed a special character).  Both passwords are the same length.  I have no desire in using a password manager.

**Comment by johnsaigle** [comment] 2020-01-29 17:41
@thomasbeaudry I just issued #5974. Do you mind reviewing to let me know if my changes are more clear?

**Comment by driusan** [comment] 2020-01-29 18:53
I agree with @gdevenyi .. this suggests that the NIST standards aren't being followed and that ticket should be re-opened. There shouldn't be complexity requirements.

**Comment by driusan** [comment] 2020-01-29 18:56
Actually wait, I reread the thread and now I no longer think that. The entropy requirements fall under the part of the document I quoted in the other ticket.

> When processing requests to establish and change memorized secrets, verifiers SHALL compare the prospective secrets against a list that contains values known to be commonly-used, expected, or compromised. For example, the list MAY include, but is not limited to:
>
>    Passwords obtained from previous breach corpuses.
>    Dictionary words.
>    Repetitive or sequential characters (e.g. ‘aaaaaa’, ‘1234abcd’).
>    Context-specific words, such as the name of the service, the username, and derivatives thereof.
>
> If the chosen secret is found in the list, the CSP or verifier SHALL advise the subscriber that they need to select a different secret, SHALL provide the reason for rejection, and SHALL require the subscriber to choose a different value.

The problem is that the reason isn't sufficiently clear.

**Comment by johnsaigle** [comment] 2020-01-29 18:58
I agree. https://github.com/aces/Loris/issues/5761 should fix that which is held up by #5214
