### ISSUE TITLE
[conflict_resolver] Error running scoring algorithmError running scoring algorithm

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#4660] opened 2019-05-21 16:48 UTC
On the test.loris.ca I'm unable to save the "Correct Answer" inside the Unresolved conflicts panel in the Conflict Resolver module.

I believe this is actually a problem with how the test.loris.ca is setup because debugging the error output, points me to the NDB_BVL_Instrument.cass.inc at line 365. Seems the file_exists($scorer) isn't finding the .score file for the instrument of the correct answer that's being updated by the user on the frontend.

I'm not getting the error when testing on my installation of LORIS.

**Comment by driusan** [comment] 2019-05-21 17:38
The conflict resolver just instantiates the instrument and calls the score() function on it. The default score function checks if a file named $InstrumentName.score exists, and if so runs it with the commentID as an argument.

The error suggests that there's a problem with the setup on the server where there is a file on the server named project/instruments/testname.score (otherwise it wouldn't try to run it), but it either isn't executable or isn't returning with a "success" exit code.

**Comment by ridz1208** [comment] 2019-05-28 14:08
this seems to be an issue with the instrument itself, I will look into it

**Comment by driusan** [comment] 2019-06-05 15:11
@ridz1208 any update on looking into it? If it's a bug with the instrument/setup, it would be good to know, because if it's not it's pretty critical for the release to have scoring of instruments work

**Comment by ridz1208** [comment] 2019-06-05 15:33
@driusan no it's not critical, if the conflict resolver can be tested with another instrument
I'll work on fixing the bmi later

**Comment by cmadjar** [comment] 2019-06-06 19:36
@driusan @maltheism @ridz1208 I tested it on mri_parameter_form and radiology_review which don't have any scoring associated to the on test.loris.ca. The conflict resolver seem to work for those instance.

Additionally, I tested the scoring on my sandbox which is identical to the DB on test.loris.ca and got the same error. Fixing the permission resolved the issue so I fixed it on test.loris.ca as well.

Closing the issue since it was a bug related to test.loris.ca VM and not a bug in LORIS

**Closed by cmadjar** 2019-06-06 19:36 UTC
Labels: 21.0.0 Testing, Bug Fix
