### ISSUE TITLE
[DQT] - Add all button does not work for a second instrument

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8009] opened 2022-02-21 20:11 UTC
**Describe the bug**
A clear and concise description of what the bug is
When you select an instrument and use the "add all" to add all the fields, it works fine. If you then select a second instrument and use "add  all" it does not work anymore.  

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
go to dqt, add the screening_moca, add all fields for the initial_assessment_screening. 
Then select another instrument, ctu_screening_montreal_cognitive_assessment for instance, and then try to add all the fields using the "add all"... It does not work :(

**Comment by ridz1208** [comment] 2022-03-09 18:10
@charliehenrib can not reproduce this issue on ccna-dev nor tes-loris-dev. Please confirm the issue is still happening and close the issue if it's not the case

**Closed** 2022-03-10 14:51 UTC
Labels: Bug, 24.0.0-bugs
