### ISSUE TITLE
[mri_violations] Changing Resolution Status of not unresolved scan creates multiple entries in table

### ISSUE THREAD

**Issue by AlexandraLivadas** [aces/Loris#9094] opened 2024-02-27 11:47 UTC
When you change the resolution status of a violated scan that is already "resolved (already has a status other than unresolved), two entries appear in the table for the same scan. This does not happen with Unresolved scans, which get updated correctly. Here is a full example with screenshots:

1. A scan exists with status "Rejected"
![Screenshot 2024-02-27 at 12 05 08](https://github.com/aces/Loris/assets/35467361/796bb8ad-d7d0-407f-ac23-f23cb4a6b56c)

2. When you update this status to "Reran" and reload the page, two entries appear for the same violation:
![Screenshot 2024-02-27 at 12 05 26](https://github.com/aces/Loris/assets/35467361/c371e389-4bea-41da-b7d0-61b647f08730)

3. Then when you try to update that new entry, before reloading it appears that the "first" entry with status Rejected gets updated:
![Screenshot 2024-02-27 at 12 05 47](https://github.com/aces/Loris/assets/35467361/ca06641e-2b51-41e3-9fb7-c920033ae3db)

4. Then when you reload the page, the second entry (with initial status Reran) is updated to the new status
![Screenshot 2024-02-27 at 12 06 04](https://github.com/aces/Loris/assets/35467361/a0ac5080-450f-44e0-b5fb-c749ed4c196f)

I'm not sure if this is an issue with how the table is populated in the frontend or the backend, I will update this issue as I do more digging.

**Comment by cmadjar** [comment] 2024-02-27 21:57
@kongtiaowang @AlexandraLivadas is it possible that the following script has not been run on the test data?

https://github.com/aces/Loris/blob/main/tools/single_use/update_violations_resolved_hashes.sql.php

If so, that could explain the duplication behaviour as the hashes in violations_resolved need to be updated.

**Comment by AlexandraLivadas** [comment] 2024-02-29 15:12
@cmadjar I just ran this script on my VM and it did not resolve the error.

**Comment by cmadjar** [comment] 2024-03-26 15:01
Tried to reproduce on my sandbox but could not. Here is what I did:

- refreshed RB data and saved a violation (it did create a duplicate that I removed before continuing the tests)
- ran `php update_violations_resolved_hashes.sql.php` 
- retest saving a violation - it did not create a duplicate anymore

I will send a PR to fix the `violations_resolved` table of RB but I cannot reproduce the issue with the latest code of LORIS once I run the script to update the hashes in violation resolved.

**Comment by cmadjar** [comment] 2024-03-28 19:05
Cool! Thanks for testing again @AlexandraLivadas 

@driusan I am closing the issue since this is not a bug. Feel free to reopen if you disagree :-)

**Closed by cmadjar** 2024-03-28 19:05 UTC
Labels: Bug, 26.0.0-bugs
