### ISSUE TITLE
[Issue Tracker] Incorrect behaviour of issue tracker dashboard widget

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#6700] opened 2020-06-09 13:38 UTC
**Describe the bug**
I log in as a user that has access to the issue tracker module and that currently has issues assigned to him. On the dashboard, I click on the issue tracker widget in the My Task panel. I am redirected to the issue tracker module, but on the 'All Issues' tab.

**To Reproduce**
See above.

**What did you expect to happen?**
I was expecting to be redirected to the issue tracker module, tab 'My Issues' (even the url seems to indicate so).

**Comment by HenriRabalais** [comment] 2020-06-11 15:42
#6541 should address this issue. However, because it introduces a larger design concept of `Filter Presets`, perhaps it should be broken up so that this issue can be addressed right away.

**Comment by driusan** [comment] 2020-06-12 20:10
Seems to be a duplicate of  #6695, just accessed from a different link.

**Comment by HenriRabalais** [comment] 2020-06-15 16:11
@driusan I'm not sure if it's exactly the same issue. The issue you linked #6695 seems to have to do with documentation while this issue has more to do with the needing to pass filter parameters via the url link in the widget to load the module with the proper filter values.

**Comment by driusan** [comment] 2020-06-15 16:50
My interpretation was that both issues are basically "the tab in the URL isn't loading properly".. @nicolasbrossard, thoughts? If I'm misinterpreting and you think they're really 2 distinct issues feel free to re-open.

**Comment by nicolasbrossard** [comment] 2020-06-15 18:20
I do not think this is a duplicate of #6695. The filter parameters are actually set properly, it is just that the wrong tab is being shown (`All Issues` instead of `My Issues`).

**Closed** 2020-07-22 16:26 UTC
Labels: Bug
