### ISSUE TITLE
[mri_violations] dashboard widget broken

### ISSUE THREAD

**Issue by christinerogers** [aces/Loris#7920] opened 2021-12-14 17:03 UTC
on the 24 testing vm: 

On the Dashboard : Mri violations widget shows 173 violations.  Clicking on the link leads to the module with "No Results found" 
 - which does not make sense given 173 violations are listed on the dashboard.
(The filter values shown also do not make sense, may be the last filter state settings are not getting reset?)

This should be escalated because... it's a Dashboard widget and so pretty prominent.  

( Might be related to / caused by #5166 )

**Comment by ridz1208** [comment] 2023-01-17 15:23
@driusan we are only as strong as our weakest link

**Comment by AlexandraLivadas** [comment] 2024-02-02 17:20
@driusan I cannot reproduce this bug (probably since mri_violations was re-written for 25). I am closing this issue

**Closed by AlexandraLivadas** 2024-02-02 17:20 UTC
Labels: Bug, 24.0.0-bugs
