### ISSUE TITLE
[survey_accounts] BMI Calculator missing questions / Cannot submit BMI survey

### ISSUE THREAD

**Issue by suzanne-lee** [aces/Loris#7667] opened 2021-10-01 16:23 UTC
**Describe the bug**
The BMI Calculator survey is missing questions and therefore cannot be submitted. 

<img width="1339" alt="BMI Calculator on test-loris-dev loris ca" src="https://user-images.githubusercontent.com/29237731/135654538-66e3bcae-29df-4bbe-9c51-272baad4611b.png">

**To Reproduce**

1. Go to the survey accounts module and click a BMI calculator survey 

- 1. If you select "Metric" as the measurement, the error "Error running scoring algorithm" appears at the top left corner of the page.
<img width="1248" alt="BMI Calculator Error running scoring algorithm" src="https://user-images.githubusercontent.com/29237731/135654742-8721e5c4-c223-4572-83d4-2010d29d909f.png">

- 2. If you select "Imperial" as the measurement, the error "Update statement did not execute successfully" appears 
<img width="1309" alt="BMI Calculator Update Statement did not execute successfully" src="https://user-images.githubusercontent.com/29237731/135654754-4034502c-a098-44b4-acf3-02ee6db3ae0c.png">

**What did you expect to happen?**
Expected height and weight fields to appear. Here is what the BMI Calculator looks like on demo.loris.ca:

<img width="1338" alt="BMI Calculator on demo loris ca" src="https://user-images.githubusercontent.com/29237731/135654582-480ffd6a-c601-4732-b98e-85ff166ee469.png">

**Browser Environment**
- Chrome 93.0.4577.82
- Firefox 92.0.1

**Comment by ridz1208** [comment] 2021-11-03 20:26
@suzanne-lee it seems like the BMI is now a 4 page instrument. This might be a bug where the survey module is not properly reading the number of pages in LINST instruments

**Comment by ridz1208** [comment] 2021-11-03 20:27
Confirmed. https://github.com/aces/Loris/blob/main/htdocs/survey.php#L101

This should be querying the instrument's getSubtestList() function instead

**Comment by ridz1208** [comment] 2021-11-04 18:52
related to https://github.com/aces/Loris/issues/7773

**Comment by suzanne-lee** [comment] 2021-11-05 15:33
@ridz1208 I don't think the issue is that NumPages is not currently using getSubtestList, as hard coding the number of pages doesn't solve the problem

**Comment by ridz1208** [comment] 2021-11-05 17:02
where did you hardcode it ?

**Comment by suzanne-lee** [comment] 2021-11-05 17:03
at line 101 (replacing the DB pselectone)

**Comment by ridz1208** [comment] 2021-11-05 17:05
This will need deeper investigation then. try to look into it and let me know if you get stuck

**Comment by suzanne-lee** [comment] 2021-11-08 14:26
Was it an intentional decision to make the BMI calculator render in 4 pages instead of 1?

**Comment by ridz1208** [comment] 2021-11-10 14:40
I took this on, PR linked above

**Comment by driusan** [comment] 2021-11-16 14:58
The above PR was broken down, the critical part is fixed by #7819. Removing critical on this, because the PR is tagged critical.

**Closed** 2022-11-10 14:56 UTC
Labels: Bug, 24.0.0-bugs
