### ISSUE TITLE
[mri_violations] Cannot resolve any MRI violation

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#8626] opened 2023-04-12 16:46 UTC
I accessed the MRI violations module and tried resolving a couple of violations but every time it fails. I keep getting this error in the JS console:
```
POST https://test-dev-250.loris.ca/mri_violations//resolve 500 (Internal Server Error)
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `ProtocolViolationModal`. See https://reactjs.org/link/warning-keys for more information.
    at div
    at ProtocolViolationModal (https://test-dev-250.loris.ca/mri_violations/js/mriViolationsIndex.js:2722:66)
    at ProtocolModal (https://test-dev-250.loris.ca/mri_violations/js/mriViolationsIndex.js:2695:17)
    at div
    at MRIViolationsIndex (https://test-dev-250.loris.ca/mri_violations/js/mriViolationsIndex.js:8356:66)
```

**Comment by cmadjar** [comment] 2023-04-13 14:50
@nicolasbrossard where did you try the module? I just tested it on testing and it works as expected.

**Comment by cmadjar** [comment] 2023-04-13 19:11
After looking into the code more closely, the problem is due to the fact that for file `assembly/300170/V1/mri/native/demo_300170_V1_dwi65_001.mnc` with time run="2019-05-23 17:57:22" there are two protocol violations: echo time and repetition time out of range, hence there is two rows for that file in the MRI violations menu table:
![Screen Shot 2023-04-13 at 2 59 41 PM](https://user-images.githubusercontent.com/1402456/231857363-38573144-47d2-4083-a0b6-11c8798181f1.png)

When we select a "resolution status" for the first row, the two gets highlighted because they have the same hash (built on PatientName, MincFile, TimeRun and SeriesUID)
![Screen Shot 2023-04-13 at 3 06 30 PM](https://user-images.githubusercontent.com/1402456/231858713-00cf1f93-e705-480e-9e84-d7b010969b8b.png)

Then, in the post request, the "hash" and the "value" to be saved in violations resolved table is sent and the query that looks for the LogID associated to the hash returns 2 rows instead of 1 here throwing a 500 error because the query is run through a pselectOne: https://github.com/aces/Loris/blob/2bf76bb879ff214fc58020116f80daf4f0e9affc/modules/mri_violations/php/resolve.class.inc#L112

Possible solutions:
1. instead of using pselectOne to query the violation table, query all IDs for the file and update/insert into violations_resolved the resolution status for all rows. Technically, it should be the same resolution for the same file
2. modify the hash to add the `header` and `value` fields of the `mri_violations_log` table but that would require a patch for existing resolved violations as the hash will change

@driusan @nicolasbrossard thoughts?

**Comment by nicolasbrossard** [comment] 2023-04-13 19:55
Solution #1 sounds good to me.

**Comment by cmadjar** [comment] 2023-04-21 15:55
Plan discussed at the imaging call today:
- [ ] only display one row per file/run when multiple protocol violations in the main table
- [ ] loops through all violations for the same file/run and update them with the same resolution
- [ ] modify hash logic to use SeriesUID/PhaseEncodingDireciton/EchoTime/EchoNumber for unique file hash
- [ ] create a script that will modify the hashes in violations_resolved to the new hash

And the fun shall begin :-)

**Comment by driusan** [comment] 2023-05-11 15:20
PR merged

**Closed by driusan** 2023-05-11 15:20 UTC
Labels: Bug, Critical to release, 25.0.0 - Bugs
