### ISSUE TITLE
[Login] request-account post is sent when form not complete

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#4512] opened 2019-05-13 15:13 UTC
POST is sent when the request-account form hasn't been filled out.
https://github.com/aces/Loris/projects/19#card-21296846

**Comment by kchatpar** [comment] 2019-05-16 18:21
@maltheism We can't reproduce the error. Could you explain how where you're seeing the post request? @zaliqarosli

**Comment by maltheism** [comment] 2019-05-17 14:13
Hi @kchatpar when visiting http://localhost/login/request-account/ and clicking the "Request Account" button. My apache access.log contains this:
`::1 - - [17/May/2019:10:09:47 -0400] "POST /login/request-account/ HTTP/1.1" 200 5938`

**Comment by zaliqarosli** [comment] 2019-05-17 17:37
@maltheism i'm not sure but could this be because the `_validate()` function in `RequestAccount` class needs to be called? it looks to me that the form doesn't actually submit because the validate function returns errors

**Comment by zaliqarosli** [comment] 2019-05-17 17:40
we could make the fields required inputs but then the browser takes over the front-end validation and will provide its own errors instead of our own custom ones. what should we do?

**Comment by maltheism** [comment] 2019-05-17 20:36
Hi @zaliqarosli I thought it was not good design to allow a post from the frontend when nothing is included in any of the fields. I think adding "required" to the input tag does make the form require something from the user and chrome likely handles the notification that the field needs a value. Sorry about the late response.

**Comment by zaliqarosli** [comment] 2019-05-21 16:35
PR fix https://github.com/aces/Loris/pull/4659

**Comment by driusan** [comment] 2019-05-21 20:00
Fixed by the above

**Closed by driusan** 2019-05-21 20:00 UTC
Labels: 21.0.0 Testing, Bug Fix, PR sent
