### ISSUE TITLE
[data_release] LORIS configuration settings are invalid or missing

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#5612] opened 2019-11-12 15:42 UTC
on: https://test-loris-dev.loris.ca/
Grant user only "Data Release: Upload file" permission.
Login use the user account, click on "Tools"--> "Data Release", the following error shows:
`LORIS configuration settings are invalid or missing and as a result execution cannot proceed. Please contact your project administrator and/or verify your LORIS configuration.`

The same thing happens if grant user only "Data Release: Grant other users view-file permissions" permission, or grant both of the two permissions.

**Comment by johnsaigle** [comment] 2019-11-12 16:53
I was able to confirm this locally. The issue is being caused because the `data_release_view` permission doesn't seem to exist according to the code. This is weird because https://github.com/aces/Loris/pull/5557 introduced this permission and it was added into Raisinbread.

I'll debug this further.

**Comment by johnsaigle** [comment] 2019-11-12 16:59
When I sourced Raisinbread again on `22.0-release` and created a new user with only the `data_release_view` permission, the module loaded and I did not get this error.

It's possible that Raisinbread needs to be refreshed on the test VM

**Comment by johnsaigle** [comment] 2019-11-12 17:13
@ridz1208 says that this is now fixed on the Test VM. There's a patch in `SQL/New_patches/` that was run to fix this issue.

**Closed by johnsaigle** 2019-11-12 17:13 UTC
Labels: 22.0.0 TESTING, Bug
