### ISSUE TITLE
[statistics] Breakdown of Registered Candidates table always shows 0

### ISSUE THREAD

**Issue by coreyAbout** [aces/Loris#4546] opened 2019-05-13 18:58 UTC
[TestPlan Demographic Statistics section
](https://github.com/aces/Loris/blob/minor/modules/statistics/test/TestPlan.md#demographic-statistics) 3 & 4

Problem:
Breakdown of Registered Candidates table always shows 0 no matter which option was selected.

**Comment by jftunteng** [comment] 2019-05-27 19:47
@coreyAbout closing this issue since the PR is merged. Feel free to reopen if this is still an issue or if it reoccurs.

**Comment by kchatpar** [comment] 2019-06-07 17:24
The statistics breakdown table in the demographics tab is still not being populated I'm getting the message on the front end:
Oops
It seems like the scan type selected does not have a corresponding column in the mri_parameter_form table in the database.
In order to display the statistics for the scan type, make sure the mri_parameter_form table contains a column in the exact format SCANTYPE_Scan_done

**Comment by ridz1208** [comment] 2019-06-17 16:08
@kchatpar that is intended behaviour, the error message tells you that your mri_parameter_form instrument does not have the necessary data for your scan types

@kongtiaowang 's #4800 should allow you to load the table, or you could do it yourself by adding the missing columns and some data in them

**Comment by ridz1208** [comment] 2019-06-17 17:19
@kchatpar I see that you reported this issue twice, im closing this one and copying my comment to the new one

**Closed by ridz1208** 2019-06-17 17:19 UTC
Labels: 21.0.0 Testing, Bug Fix, PR sent
