### ISSUE TITLE
[Core] TypeError causes 500 response when installing an instrument via Instrument Manager

### ISSUE THREAD

**Issue by johnsaigle** [aces/Loris#5698] opened 2019-11-19 22:47 UTC
>PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Utility::associativeToNumericArray() must be of the type array, string given, called in /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc on line 912

Also there are issues in the module with bad filepath to the page decorators:
> PHP Fatal error:  Uncaught Error: Class 'LORIS\\Http\\Response\\Conflict' not found in /var/www/loris/modules/instrument_manager/php/instrument_manager.class.inc:174

This should be JSONResponse, not response

**Comment by johnsaigle** [comment] 2019-11-19 22:51
This is triggered when `EnableCertification` is set to `1` in the config file and the `CertificationProjects` and `CertificationInstruments` are empty.

I'm not sure the correct values for these settings.

**Comment by kongtiaowang** [comment] 2019-11-20 17:36
@johnsaigle 
I can't reproduce this issue when EnableCertification is set to 1 or 0.

**Comment by driusan** [comment] 2019-12-13 16:27
PR was merged 23 days ago.

**Closed by driusan** 2019-12-13 16:27 UTC
Labels: 22.0.0 TESTING, Bug, PR sent
