### ISSUE TITLE
[Issue Tracker] Submit issue shows an error but the issue is still created

### ISSUE THREAD

**Issue by AlexandraLivadas** [aces/Loris#4735] opened 2019-05-29 18:40 UTC
When creating a new issue and clicking "Submit Issue", an error pop-up appears saying "Failed to submit issue" and the console has this error:
<img width="731" alt="Screen Shot 2019-05-29 at 2 39 51 PM" src="https://user-images.githubusercontent.com/35467361/58582388-a2e4a000-821f-11e9-8ced-72e2bad860aa.png">

But, when you look at the issue list, the issue still appears correctly!

Edit: This error does not show up if you assign the issue to another user. For example, if I am logged in as admin and assign another user, a success message pops up and I am redirected to the Issue Tracker page.

**Comment by maltheism** [comment] 2019-05-29 20:24
I thinks this PR: https://github.com/aces/Loris/pull/4690 fixes this.

**Comment by driusan** [comment] 2019-06-07 19:08
I believe #4819 also fixes this (though I can't reproduce this exactly.. I don't get a generic error, I get nothing at all if the assignee is the current user)

**Comment by cmadjar** [comment] 2019-06-18 18:00
#4819 got merged and fixed the issue so closing that issue

**Closed by cmadjar** 2019-06-18 18:00 UTC
Labels: 21.0.0 Testing, Bug Fix, PR sent
