### ISSUE TITLE
Unable to configure user and admin on new install

### ISSUE THREAD

**Issue by pn2200** [aces/Loris#6539] opened 2020-05-14 19:09 UTC
**Describe the bug**
Cannot create non-administrator user or LORIS admin account on installdb.php page after a brand new installation.

**To Reproduce**
I followed the [installation guide](https://acesloris.readthedocs.io/en/latest/wiki/00%20-%20SERVER%20INSTALL%20AND%20CONFIGURATION/01%20-%20LORIS%20Install/Ubuntu/). I installed on Ubuntu 20.04. After the database setup step, the instructions are: 

> Click submit, and on the next screen that is presented, follow instructions to enter the username and password of your LORIS database user and front-end admin user.

When I do that, the page displays an "All entries must be provided" error message, even though all entries are provided. See screenshot:
<img width="629" alt="Screen Shot 2020-05-14 at 11 56 00 AM" src="https://user-images.githubusercontent.com/489253/81974849-fab81a80-95da-11ea-84ac-46776111b744.png">

There are no errors in the loris-error.log. There is no config.xml file in /var/www/loris/project.

**What did you expect to happen?**
I expected the users to be created, the config.xml file to be created, and I would expect to be able to go to the next configuration step.

**Browser Environment (please complete the following information):**
- OS: Ubuntu 20.04LTS
- Browser: Firefox 75.0
- Version: 22.0.1

**Server Environment (if known):**
- LORIS Version: 22.0.1
- Linux distribution and Version: Ubuntu 20.04LTS
- MySQL/MariaDB Version: MySQL 8.0

**Comment by lingma** [comment] 2020-05-14 20:23
You can create the user `rethinkuser` with your password and check the "Already created" to retry.

**Comment by lingma** [comment] 2020-05-14 20:31
There is a note about possible problem for MySQL 8.0 in the Readme.md: "If you use MySQL 8, please read this link..." Please refer to the Readme.md to check.

**Comment by pn2200** [comment] 2020-05-14 21:15
Unfortunately, checking the box "Already Created" and retrying does not change the result. The page still displays the error "All entries must be provided", the config.xml file is not created and there are no errors in the loris-error.log file.

Perhaps I am not understanding your suggestion. Are you suggesting that I manually create the user in mysql first?

Also, the links regarding MySQL 8 ([this link](https://www.php.net/manual/en/mysqli.requirements.php) and also [this](https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password-compatible-connectors)) do not appear to apply, because PHP version is 7.4.3, and these documents say the incompatibility occurs with earlier versions of PHP.

**Comment by lingma** [comment] 2020-05-14 21:28
I believe that Loris 22.0 is tested based on MySQL 5.7, PHP 7.2 and PHP 7.3. The MySQL 8.0 note was intended for the DB user connection method, I suspect which might be the cause of your problem. I don't believe that PHP7.4 is available when Loris 22.0 was released, so I don't think the Loris 22.0 was tested against PHP 7.4, which usually won't cause much problem with upgrading.

As a result, I suggest you to create the admin db and general db user first to try, if the installation works, then the general db user creation might be the cause, which I suspect is the cause of your problem. Even if the issue is reported as a bug, since the environment was not the one v22.0 released, I don't think this could be considered a bug to v22.0 and I don't think Loris team maintains too much old versions. I believe you could find a trick to install with PHP7.4, unless which doesn't work, which I doubt less, then I could try to install on PHP7.4 by myself to help you further.

**Comment by lingma** [comment] 2020-05-14 21:39
Yes, I suggested you to create db user manually in MySQL first then come back to the installation interface.

**Comment by pn2200** [comment] 2020-05-14 22:33
The database user `rethinkuser` is actually created on the first attempt of using the installation interface. Creating a new user, manually in mysql with
```
create user 'newuser'@'localhost';
grant all on rethink.* to 'newuser'@'localhost' identified by 'password';
flush privileges;
```
doesn't change anything. The same error message occurs in the installation interface and the config file is not created.

If I manually create a user in mysql, without the granting any privileges, the error is "The specified user does not exist or is using an incorrect password or the database does not exist".

I think at the very least there is a bug in the error handling here: The error message isn't accurate because all the fields are provided. The error message isn't helpful because is doesn't indicate what the problem is or how to fix it.

I think there is also a bug because the installation will not proceed with either the manually created user or the user created from the installation interface.

How can I proceed? I'm not trying to be difficult in the choice of MySQL version or PHP or anything. I am using only what is installed by default in Ubuntu 20.04.

**Comment by lingma** [comment] 2020-05-14 23:12
I know that the default error message is what you have seen, the message only wanted to say something wrong with "you have to fill all".

I just tried PHP7.4, all works fine. So I suspect that the problem lies in the MySQL 8.0, which I could only try a little later, I am not willing to kill my DB on my workstation to do the test.

**Comment by lingma** [comment] 2020-05-14 23:19
By the way, I have installed on MySQL 8.0 together with PHP7.3 (Ubuntu 18.04), the installation MySQL note in Readme.md was added by me, I am quite confident that the Loris supports MySQL 8.0 + PHP7.4, I don't know what goes wrong now.

**Comment by lingma** [comment] 2020-05-16 03:28
Hi Paul, I just installed Loris 22.0.1 on a fresh Ubuntu 20.04 + MySQL 8.0 + PHP 7.4 without any difficulty, with/without DB user pre-created. I don't know what caused your difficulty, I believe the problem might have something to do with your file system permission settings, please check. Though there is something to improve in the error message handling, I believe the installation should normally work.

**Comment by pn2200** [comment] 2020-05-16 17:16
Okay, thanks for trying to install. I will try again. 

Do you have any suggestions what file permissions need modification? The /var/www directory? The MySQL database data directory?

**Comment by lingma** [comment] 2020-05-16 18:04
You are welcome. You can post your question to loris dev team group email if you have detailed further question. I believe that the email address is loris-dev@bic.mni.mcgill.ca. You can check for clarification if the address I just got from web is not reachable.

I believe if you follow the installation guide, the installation should be fine. The installation looks like a general website management system, I did not touch anything. You might need to have some MySQL knowledge to manage DB. As to the file permission, the `tools/install.sh` will take care of the usual permission issue, unless you are not using Apache2, you will need to manage /var/www/loris permission by yourself in this case. I will never suggest you to modify MySQL database data directory for any reason.

**Comment by lingma** [comment] 2020-05-16 18:37
Supposing that you install the loris at `/var/www/loris`, the webserver process need to be able to write to `/var/www/loris/project` to finish the installation with a config file, you will need to make sure that the directory is writable by the web server process, which will depend on your situation, possibly Apache2 default user www-data or other user, but in most cases with Apache2 you don't need to check that, that task should have been taken care of by the `tools/install.sh`.

**Comment by lingma** [comment] 2020-05-17 13:22
I just made a test, even if the /var/www/loris/project` is not writable by the web server process, the installer could still go ahead with further instructions. Currently I have no idea what causes your difficulty, you might need to start over from the beginning and follow the installation guide.

**Comment by christinerogers** [comment] 2020-05-19 15:09
Hi @pn2200 -- 
For install support or questions for a specific instance/use case of LORIS, please contact our community support mailing list at : loris-dev [ at ] bic.mni.mcgill.ca 
We'll be happy to go over with you there the troubleshooting you've done so far and what to check next. 
Please link to this issue when you write us there. 
Thanks!

**Comment by johnsaigle** [comment] 2020-05-19 16:00
@christinerogers if this conversation continues on the mailing list then it would be good to post the full conversation and resolution here so that other users can find an answer if they encounter this in the future.

**Comment by christinerogers** [comment] 2020-05-21 16:05
@pn2200 again inviting you to please get in touch through our support channels -- loris-dev [at] bic.mni.mcgill.ca or even loris.info [at] mcin.ca 
We'll be very happy to follow up on your stack and the issues you're encountering.  Even if it's working now, your input there to help fix our error messaging would be quite valuable with a few more details. 

Closing this issue for now, since we're unable to reproduce the steps performed that triggered this issue, and the individual has not responded.

**Closed by christinerogers** 2020-05-21 16:05 UTC
Labels: Bug
