### ISSUE TITLE
[dataquery] "Load Saved Query" not working

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris#5502] opened 2019-11-01 22:03 UTC
When clicking on "Load Saved Query" and selecting the queries saved for the user, the DQT complete crashes (blank page).

**Comment by johnsaigle** [comment] 2019-11-05 22:19
I'm not able to replicate this on my VM or on demo, but the issue occurs on the Test VM. It's possible that it's configured incorrectly.

**Comment by cmadjar** [comment] 2019-11-06 13:40
@kongtiaowang Could you look into why this is not working on testing? Thanks!

**Comment by ridz1208** [comment] 2019-11-06 15:41
@johnsaigle demo is on 21

**Comment by johnsaigle** [comment] 2019-11-06 15:51
Good to know. Still seems to work when I check out 22.0-release locally.

**Comment by johnsaigle** [comment] 2019-11-11 19:53
Seems to be an issue on the Test VM, not the code.

**Comment by johnsaigle** [comment] 2019-11-12 17:24
@ridz1208 @kongtiaowang Could one of you verify this on the back-end of the test VM? It would be good to check whether the test VM is set up correctly. Checking the error log will help.

**Comment by ridz1208** [comment] 2019-11-12 17:32
@johnsaigle I wouldn't even know what to look for.

any suggestions ?

**Comment by johnsaigle** [comment] 2019-11-12 17:37
I would just click "Load Saved Query" and see what the error log says. I imagine there's a 500 error happening because the module doesn't load anything on that VM

**Comment by ridz1208** [comment] 2019-11-12 17:40
I was trying right now and the User Saved Queries is not actually a button

**Comment by johnsaigle** [comment] 2019-11-12 17:42
> Load Saved Query

that's the button. "User Saved Queries" is a header separating links that are supposed to appear.

<img width="163" alt="Screen Shot 2019-11-12 at 12 42 21" src="https://user-images.githubusercontent.com/4022790/68695910-e458d580-0549-11ea-9eed-7d7d73414e72.png">


"test" and "admin: testquery2" are the links.

**Comment by ridz1208** [comment] 2019-11-12 17:49
I dont have either of those
ill create one

**Comment by ridz1208** [comment] 2019-11-12 17:50
I tried it out, I'm having no issues
![Screenshot from 2019-11-12 12-50-16](https://user-images.githubusercontent.com/15268287/68696452-043cc900-054b-11ea-9b1d-2f2363a1811b.png)

**Comment by ridz1208** [comment] 2019-11-12 17:51
@cmadjar could you try it again ?

**Comment by maltheism** [comment] 2019-11-12 18:01
@ridz1208 I'm having issues when click on the "Load Saved Query" button on my setup of LORIS for the DQT. The "User Saved Queries" & "Shared Saved Queries" menu options are unresponsive. So I think the issue still exists.

**Comment by johnsaigle** [comment] 2019-11-12 18:02
It's possible that your VM isn't set-up to connect to CouchDB properly. Does your error log show anything?

**Comment by maltheism** [comment] 2019-11-12 18:06
@johnsaigle I just checked and error log is empty. The Define Filters has data in it. Similar with the Define Fields. The frontend isn't outputting any errors to console as well.

**Comment by johnsaigle** [comment] 2019-11-12 18:15
Hm alright. I wonder if maybe the JS didn't get compiled?

If it did, we should improve error handling in this module.

**Comment by ridz1208** [comment] 2019-11-12 18:59
https://github.com/aces/Loris/pull/5399

**Comment by ridz1208** [comment] 2019-11-12 18:59
these might be related
theres a PR going to 21 for it

**Comment by cmadjar** [comment] 2019-11-13 13:55
I retested it on test-loris-dev.loris.ca. I had to save first a query and then loading the saved query worked. 

However, on testing there is an `admin_` query in the saved queries that does not have any fields defined and when I click on this one, I get a blank page... Probably testing or RB related? @ridz1208?

**Comment by ridz1208** [comment] 2019-11-13 14:32
@cmadjar honestly i dont have the DQT knowledge to know... @driusan any ideas ?

**Comment by driusan** [comment] 2019-11-13 18:05
I would guess either #5399 related or a similar issue when there's an empty query present.

**Comment by ridz1208** [comment] 2019-11-14 02:50
I put discussion required cuz at this point i'm not sure anymore how to get this through, noone seems to be able to test it properly and i never know which bugs are completely unrelated and which are caused by this

**Comment by kongtiaowang** [comment] 2019-11-15 19:25
@ridz1208 I debug it on testing VM. It seems like that is the only one CouchDB works fine.

**Comment by driusan** [comment] 2019-11-18 15:25
Now that it's merged, was this fixed by #5399?

**Comment by ridz1208** [comment] 2019-11-19 19:28
seems to be fixed on dev

**Closed by ridz1208** 2019-11-19 19:28 UTC
Labels: 22.0.0 TESTING, Bug, Critical to release, PR sent
