### ISSUE TITLE
Permission to see a session's instrument list should involve user's and session's project

### ISSUE THREAD

**Issue by nicolasbrossard** [aces/Loris#6934] opened 2020-08-25 18:50 UTC
**Describe the bug**
Found on branch `main` using RB data.

I logged in as a user that has `access_all_profiles` and that is associated to a single project: `Challah`. I can access the instrument list of candidate DCC090 at visit `V3` (performed in the context of project `Pumpernickel`) by typing the following URL in my browser:

http://my_vm_host/instrument_list/?candID=587630&sessionID=1655

**What did you expect to happen?**
A page saying that I do not have permission to view this should have been displayed.

**Comment by christinerogers** [comment] 2020-08-26 17:03
@laemtl is this partially addressed by your PR on project permissions? (and please could you link it here?)

**Comment by laemtl** [comment] 2020-08-26 17:52
@christinerogers No it's not. #6836 only update the dropdown filters. I think this issue is caused by a missing check in the has_access function.

**Comment by laemtl** [comment] 2020-08-26 17:56
@nicolasbrossard I think this issue is a duplicate of #6880

**Comment by zaliqarosli** [comment] 2021-12-07 17:24
i think this ticket can be closed because from testing https://github.com/aces/Loris/issues/7786, the module's test plan and readme both specify:

```
One of the following conditions must be met to have access to the module:

The user has the permission access_all_profiles
The user shares a project and site with the visit
```

so currently, a user with `access_all_profiles` permissions should be able to see a visit outside of their associated project. if this should not be the case, then it's more a change request than a bug

**Comment by ridz1208** [comment] 2022-01-11 21:54
closing as per Zaliqa's explanation

**Closed by ridz1208** 2022-01-11 21:54 UTC
Labels: Bug
