### ISSUE TITLE
[survey_accounts] Can not create survey

### ISSUE THREAD

**Issue by driusan** [aces/Loris#6229] opened 2020-04-02 13:18 UTC
When clicking "Add Survey" in `survey_accounts`, filling out all the fields except email address, and clicking the "Create survey" button the page reloads with all data except the instrument (which was previously selected) filled out. There is no error message and the survey is not created.

I don't have an address to use to try the "Email survey" option..

**Comment by ridz1208** [comment] 2020-04-09 23:22
@driusan I could not reproduce the error. can you reproduce it and give me exactly what was entered in each field ?

- I have tried causing errors by choosing non-exiting visits, got the proper error in red
- I have tried choosing a visit which already has the instrument, got the proper error in red
- i have tried a valid addition. survey was created successfully

**Comment by racostas** [comment] 2020-04-13 22:34
@driusan I have the same situation as @ridz1208 . I tried to reproduce the issue but it seem to be OK in my test. The survey is created successfully and the validation seem to work.

**Comment by driusan** [comment] 2020-04-15 12:25
My steps were (and I just tried again and had the same behaviour..):

1. Log in to https://test-loris-dev.loris.ca/ and go to survey module.
2. In the form enter the data:

- DCCID: 587630
- PSCID: DCC090
- Visit: V2
- Instrument: Medical History

3. Click "Create Survey"

**Comment by ridz1208** [comment] 2020-04-15 14:36
@driusan I managed to reproduce it on the test VM but not on any other (tried it on my local install and my VM)

will wait for the next round of testing and see if it happens again after latest code is pulled

**Comment by racostas** [comment] 2020-04-15 15:22
@driusan,@ridz1208. Yes, the issue is a bit funny. Not sure if data related.

The test I performed also in the official test VM.

![image](https://user-images.githubusercontent.com/37309344/79354354-4d35e680-7f0a-11ea-84cc-23e8bef1a6ec.png)

After this one I selected the Medical History instrument.

![image](https://user-images.githubusercontent.com/37309344/79354855-f250bf00-7f0a-11ea-8460-27cc314a55d6.png)

And this time it does appear in the survey accounts list.

![image](https://user-images.githubusercontent.com/37309344/79354570-90905500-7f0a-11ea-9beb-c36d6bcc85b6.png)

**Comment by HenriRabalais** [comment] 2020-04-24 21:17
I tested this and experienced the same error as @driusan.

After sourcing the data from this PR (#6345), the only remaining issue seems to be whether or not a survey should be able to be created with an associated e-mail address.

Should this be the case?

**Comment by driusan** [comment] 2020-04-27 14:34
Yes, emails are only required with the "email survey" link. You can create a survey to administer in the lab directly to the subject without an email address.

**Comment by ridz1208** [comment] 2020-04-27 16:22
@driusan so it seems like the issue has been resolved y fixing RB. If that's also your understanding please close the issue

**Comment by driusan** [comment] 2020-04-27 16:53
@ridz1208 Has the test VM been updated so I can verify before closing?

**Comment by ridz1208** [comment] 2020-04-27 17:27
i don't think so, might need to wait for round 2 then

**Comment by ridz1208** [comment] 2020-05-19 15:28
@driusan this is part of the test plan and you won't be the one re-testing it. so closing the issue for now, a new one will be created if the module is still not working

**Closed by ridz1208** 2020-05-19 15:28 UTC
Labels: 23.0.0-testing, Bug

**Comment by driusan** [comment] 2020-05-19 16:50
@AlexandraLivadas I think the survey_account testing is assigned to you in the latest email, can you make sure you verify this case when testing it?

**Comment by AlexandraLivadas** [comment] 2020-05-22 18:20
> @AlexandraLivadas I think the survey_account testing is assigned to you in the latest email, can you make sure you verify this case when testing it?

@driusan I checked (and double-checked) this case and did not run into any problems!
