### ISSUE TITLE
[imaging_qc] "An error occurred while loading the page." (for new Loris without Raisin bread))

### ISSUE THREAD

**Issue by kongtiaowang** [aces/Loris#5636] opened 2019-11-13 20:22 UTC
[imaging_qc] An error occurred while loading the page. (for new Loris without Raisin bread)).
It should remind the user to set "mri_parameter_form" table in the database.

**Comment by johnsaigle** [comment] 2019-11-13 23:14
Duplicate of #5325

**Comment by ridz1208** [comment] 2019-11-14 02:44
duplicate

**Closed by ridz1208** 2019-11-14 02:44 UTC
Labels: 22.0.0 TESTING
