### ISSUE TITLE
[data_team_helper] Pagination links are broken

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#5505] opened 2019-11-04 15:04 UTC
At the bottom of the datatable, on any tab:

1. click on the page number 1 or 2 does the same thing. 
2. the `...` can't be expended
3. clicking on the arrow at the end of the numbers displays the first page instead of the last.

**Comment by driusan** [comment] 2019-11-05 17:57
Assigned this to myself because I thought it was because of the DataTable optimizations I did.. it turns out that the data_team_helper is rolling its own react components and not using the DataTable from LORIS, so this is unrelated. (Pagination is working on LORIS DataTables)

**Comment by sruthymathew123** [comment] 2019-11-11 16:19
I think this is a duplicate of #5377

**Comment by sruthymathew123** [comment] 2019-11-11 16:21
@maltheism  I saw a PR related to this issue.  Can you confirm if a fix is already existing for this issue?

**Comment by maltheism** [comment] 2019-11-11 16:41
@sruthymathew123 my PR fixes this issue because it uses the FilteredDataTable that handles pagination.

**Comment by sruthymathew123** [comment] 2019-11-11 16:44
@Thanks Alizee, I think your PR is still open and rewriting the entire Data Team helper module. Is there a quick fix available in your PR particular for this issue.

**Comment by maltheism** [comment] 2019-11-11 17:11
@sruthymathew123 the fix for the pagination came about from using the jsx/FilterableDataTable.js in my PR. I'm not sure if that would be a quick fix for the existing code. It seems the existing code wrote custom pagination and the getPage() method is likely broken or a similar method for the custom pagination.

**Comment by driusan** [comment] 2019-11-14 18:17
should be fixed by above PR

**Closed by driusan** 2019-11-14 18:17 UTC
Labels: 22.0.0 TESTING, Critical to release, PR sent
