### ISSUE TITLE
[issue tracker] Can not edit description of already created issue.

### ISSUE THREAD

**Issue by driusan** [aces/Loris#8353] opened 2023-02-01 17:49 UTC
In the issue tracker, you can not edit the description of an issue if it's already been created, only add new comments. This is odd. Most bug tracking software lets you edit the description.

We should let users edit descriptions on issues.

**Comment by christinerogers** [comment] 2023-02-07 16:19
Hi dave, there should be a permission level that lets you edit this.  
Could you clarify what permissions you had for the issue tracker when you tested this?
(maybe your user had comment-only privilege by design)

**Comment by driusan** [comment] 2023-02-09 14:53
I have both `issue_tracker_developer` and `issue_tracker_reporter` and I don't see anywhere in the code that would make a distinction. `description` looks like it's always rendered as a static text element in the JSX.

**Comment by christinerogers** [comment] 2023-08-08 17:59
per loris meeting Aug 8
- [ ] we are adding a new field ... Rolando 
- [ ] a (one-line) patch should be committed to populate this field with the First comment. 

@racostas please update as needed.

**Closed** 2024-07-02 16:52 UTC
Labels: Proposal
