### ISSUE TITLE
[canidate_parameters] testing plan unclear

### ISSUE THREAD

**Issue by maltheism** [aces/Loris#6275] opened 2020-04-06 15:42 UTC
**Describe the bug**
Testing plan states:
```
1. Check Permissions:
    * _candidate_parameter_view_ (_View Candidate Parameters_) permission (you should not be able to edit fields)
	* _candidate_parameter_edit_ (_Edit Candidate Parameters_) permission (you should be able to edit fields)
	* You need to belong to the same site as the candidate you are accessing, unless...
	* If you have _access_all_profiles_ you should be able to access all candidate profiles (even without candidate_parameters permissions)
```
I made an account with permission "View Candidate Parameters" and I'm unable to view "Candidate Info" button to view the parameters. Similar when "Edit Candidate Parameters" is enabled and even when "Across all sites access candidate profiles" is enabled.

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. Make a new account
2. Giver permissions
3. Visit PSCID on access profile.

**Comment by maltheism** [comment] 2020-04-06 15:43
@ridz1208 or @jesscall do you happen to know if I'm not doing a necessary step for making a user account with these permissions. Does the account need a role or other permissions for it to work?

**Comment by jesscall** [comment] 2020-04-06 16:32
You should have 'Data Entry' and 'View Candidate Parameters' in order to view the button

**Comment by maltheism** [comment] 2020-04-06 19:42
@ridz1208 I believe the test plan should be modified to include the above role 'Data Entry' that's missing from the test plan.

**Comment by ridz1208** [comment] 2020-04-07 00:20
@maltheism probably the readme too

**Comment by ridz1208** [comment] 2020-04-07 18:52
To whomever is fixing this. Remove requirement for data entry permission

**Comment by cmadjar** [comment] 2020-04-24 13:31
@maltheism @driusan is this issue resolved? I see that a PR has been merged but the issue is still open. Please, close the issue if resolved or comment on what still needs to be done to resolve the issue. Thanks!

**Closed** 2020-04-24 13:57 UTC
Labels: 23.0.0-testing, Bug, Documentation
