### ISSUE TITLE
[Issue tracker] - Attachment not visible

### ISSUE THREAD

**Issue by charliehenrib** [aces/Loris#8005] opened 2022-02-21 15:01 UTC
**Describe the bug**
A clear and concise description of what the bug is
When a screenshot is attached, the file photo should appear embedded in the attachment history. Currently, it is only available through download.

**Comment by ridz1208** [comment] 2023-01-17 15:52
@kongtiaowang not super urgent but its a good feature to have

@charliehenrib this is not a bug !

**Comment by charliehenrib** [comment] 2023-01-17 17:36
@ridz1208 if you say so. I can't test it on demo.loris.ca. It does not let me upload files.

**Comment by ridz1208** [comment] 2023-01-17 17:48
@charliehenrib what do you get when you try uploading a file ?

**Comment by ridz1208** [comment] 2023-01-17 17:53
@kongtiaowang reassigned to @charliehenrib and @CamilleBeau since the feature already exists on CCNa and they just never shared it with the group

**Comment by charliehenrib** [comment] 2023-01-17 17:59
> 

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/25854264/212976014-c5803fd3-c8bf-470c-917f-e80f52cd3c46.png">

**Comment by ridz1208** [comment] 2023-01-17 18:05
@charliehenrib could you make a new ticket to improve the clarity of this error message please. I think it was caused by the upload directory being unreachable but it should be much much more descriptive. you can add the 24 bugs flag on it. I solved the issue for demo.loris.ca for now

thanks

**Closed as completed** 2023-03-28 12:36 UTC
Labels: Category: Feature
