### ISSUE TITLE
[issue_tracker] Can access issues that are not shown in the datatable

### ISSUE THREAD

**Issue by xlecours** [aces/Loris#6282] opened 2020-04-06 16:47 UTC
**Describe the bug**
As a user with Montreal as his unique site, I can access issues from an other site (ex: /issue_tracker/issue/25 ). This is either a bug or the datatable should display those issues. The permission description says: "Can add a new issue, edit own issue, **comment on all**"

**To Reproduce**
Steps to reproduce the behavior (attach screenshots if applicable):
1. With a user that have Montreal as a unique site, go to `/issue_tracker/issue/25`

**Comment by johnsaigle** [comment] 2020-04-07 19:04
@jesscall @sruthymathew123 @maltheism What would be the preferred behaviour? Should a user have all of these issues displayed in the datatable or should we disable a user commenting on issues associated with a site to which the user does not belong?

**Comment by maltheism** [comment] 2020-04-07 19:17
Hi @johnsaigle I think @LeighMac would likely know. I don't believe the issue_tracker has site permissions. I'm not sure what the intended behaviour is in that case.

**Comment by sruthymathew123** [comment] 2020-04-07 19:41
@SantiagoTG I know you are one of the person who is mostly using issue tracker on the IBIS side. Can you answer the above concern?

**Comment by SantiagoTG** [comment] 2020-04-09 14:17
I can't remember of an instance where this has been an issue. Though seldom used, we may still want to allow users from other sites to see/comment on all issues. In this manner we may avoid having duplicate tickets (if the user searches for the issue, similar to Github), so I don't see why we would want to restrict access to a given issue only to site users. Further discussion required on this one.

**Comment by ridz1208** [comment] 2020-04-09 14:22
@SantiagoTG I see your point but I also see cases where some sensitive data might be in the issue and might not be okai to share amongst other sites/projects.

I think the ideal solution is to flag the issue itself with "restrict on site" and "restrict on project" flags that would dictate who can see the issues

**Comment by SantiagoTG** [comment] 2020-04-09 14:24
I see your point, and that can be a neat, straightforward alternative solution. No objections on this.

**Comment by driusan** [comment] 2020-04-09 14:54
I think if an issue has a site set it should only be viewable by:

1. The person who created the issue
2. People at that site and
3. Watchers of the issue

**Comment by ridz1208** [comment] 2020-04-15 15:07
@johnsaigle can you issue the fix ?

**Comment by johnsaigle** [comment] 2020-04-15 16:56
It doesn't seem to me like we've landed on a desired result. This also seems more like a feature/enhancement than a bug fix.

**Comment by ridz1208** [comment] 2020-04-20 17:44
@johnsaigle I'm okai with dave's solution honestly but yeah it might be a feature unless it's specified in the test plan. could you double check the testplan when you have some time and we'll decide what to do after that

**Comment by johnsaigle** [comment] 2020-04-20 19:31
I'm not really sure what you mean. I checked the test plan. It says user should be able to comment on all issues, similar to the permission description.

As Xavier said, this is possible but when a user views the module it will not display issues from other sites. However, manually navigating to an issue will allow a user to view/comment on it.

**Comment by ridz1208** [comment] 2020-04-28 14:07
@HenriRabalais new order of business

Can you just make sure that any issue that is not displayed in the menu filter is not accessible by the user ?

ie, you cant access an issue that you don't see in the table thats it

**Comment by HenriRabalais** [comment] 2020-04-28 18:28
The condition at line `100` is always true because $this->issueID is only set in the handle function, which is called after the hasAccess function. Should we be passing the request, to hasAccess so that we can properly assess user access for a given request?

``` 
87     /**                                                                         
 88      * Checks if the user has the ability to *view* the issue page              
 89      * Does not govern editing abilities; those are controlled by issueIndex.js 
 90      *                                                                          
 91      * @param \User $user User Instance                                         
 92      *                                                                          
 93      * @return bool                                                             
 94      *                                                                          
 95      * @throws \ConfigurationException                                          
 96      */                                                                         
 97     function _hasAccess(\User $user) : bool                                     
 98     {                                                                           
 99         $issueID = $this->issueID;                                              
100         if (!$issueID) {                                                        
101             return true;                                                        
102         }                                                                       
103         $issueData = \Database::singleton()->pselectRow(                        
104             "SELECT centerID FROM issues WHERE issueID=:issueID",               
105             array('issueID' => $issueID)                                        
106         );                                                                      
107         return (is_null($issueData)                                             
108             || in_array($issueData['centerID'], $user->getData('CenterIDs'))    
109             || ($user->hasPermission('access_all_profiles'))                    
110             || (!empty($issueData['centerID']))                                 
111         );                                                                      
112     }    
```

**Comment by xlecours** [comment] 2020-04-28 18:46
@HenriRabalais IMO, adding a filter to the dataprovisioner would be the ideal way of solving this.

**Comment by driusan** [comment] 2020-04-28 18:53
@xlecours How would adding a filter to the dataprovisioner solve this? Isn't the issue that the DataProvisioner *is* filtering but users can access issues that they can't see in the menu?

@HenriRabalais I briefly looked at the code and it looks like the `setup()` function isn't written very well (ie. it's using `header()` to try and change the response value..) I think the way it's solved in other modules is by setting class variables in `process()` which is called before `hasAccess`, but I'm having trouble finding an example right now so maybe I'm mistaken..

**Comment by driusan** [comment] 2020-04-28 18:57
`modules/candidate_profile/php/candidate_profile.class.inc` is an example of a class that uses process to ensure class variables are set before hasAccess..

**Comment by ridz1208** [comment] 2020-04-28 19:16
@driusan I really don't like how it's doing it honestly.

I feel like it makes more sense to pass the $request to the hasAccess function then overload the process function.

**Comment by HenriRabalais** [comment] 2020-05-04 20:54
PR Sent.

**Closed** 2020-05-11 12:16 UTC
Labels: 23.0.0-testing, Bug
