### ISSUE TITLE
[Dicom Archive] Date Format Inconsistencies

### ISSUE THREAD

**Issue by kchatpar** [aces/Loris#5443] opened 2019-10-31 18:15 UTC
In the dicom archive the pre-set filters are dd/mm/yyyy in the table the format is yyyy/mm/dd. Filtering still works but this should be the same format.

**Comment by cmadjar** [comment] 2019-10-31 19:20
@kchatpar I am confused... I just looked at it on test-loris-dev.loris.ca and they all look formatted yyyy/mm/dd for me on Chrome and Firefox (see below). 

<img width="1152" alt="Screen Shot 2019-10-31 at 3 18 15 PM" src="https://user-images.githubusercontent.com/1402456/67978963-b7273180-fbf1-11e9-8e22-c8b41015d9ff.png">

**Comment by maltheism** [comment] 2019-10-31 20:42
@kchatpar are you referring to the "Archive Location" column of the table in the picture from @cmadjar ?

**Comment by cmadjar** [comment] 2019-11-01 19:07
@kchatpar is this still an issue? I cannot reproduce it on any browser...

**Comment by kchatpar** [comment] 2019-11-04 15:40
On my browser, it still shows up as dd/mm/yyyy
![Screenshot from 2019-11-04 10-38-43](https://user-images.githubusercontent.com/15351191/68134032-7ed46b80-feef-11e9-9632-4548db995a64.png)

**Comment by cmadjar** [comment] 2019-11-04 21:14
What browser are you using?

**Comment by kchatpar** [comment] 2019-11-04 21:46
I'm using chrome

**Comment by cmadjar** [comment] 2019-11-05 15:29
Probably a computer/browser setting, not a LORIS setting so closing this one.

**Closed by cmadjar** 2019-11-05 15:29 UTC
Labels: 22.0.0 TESTING
