### ISSUE TITLE
[instrument_list] Can't select "Send to DCC" even with initial + DDE complete and no conflicts

### ISSUE THREAD

**Issue by leighevans** [aces/Loris#5701] opened 2019-11-20 16:24 UTC
"Send to DCC" option not available even once initial and DDE are set to complete within a visit (and there are no conflicts). Permission to Send to DCC not the issue either (ensured I have it). 
Screenshots attached:

**Send to DCC option not available even with complete data for initial and DDE:**
![Screen Shot 2019-11-20 at 11 12 17 AM](https://user-images.githubusercontent.com/32552953/69256639-cada0e00-0b87-11ea-9e30-c54fa40c7f6c.png)

**No conflicts exist for this candidate preventing Send to DCC option:**
![Screen Shot 2019-11-20 at 11 12 57 AM](https://user-images.githubusercontent.com/32552953/69256683-d9c0c080-0b87-11ea-98b4-65afa0a697b8.png)

**Comment by ridz1208** [comment] 2019-11-25 18:36
this was not reproducible on other visits, turns out the issue was because of the RB data. the submitted column in the `session` table was null in some places making the code think it has been submitted.

will issue a PR to resolve

**Comment by driusan** [comment] 2019-11-27 16:02
PR merged

**Closed by driusan** 2019-11-27 16:02 UTC
Labels: 22.0.0 TESTING, Critical to release, PR sent
